In [1]:
import pandas as pd

In [2]:
#excel_file_path = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman(2021-2023).xlsx'
excel_file_path1 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2018_trackman.xlsx'
excel_file_path2 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2019_trackman.xlsx'
excel_file_path3 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2020_trackman.xlsx'
excel_file_path4 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2021_trackman.xlsx'
excel_file_path5 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2022_trackman.xlsx'
excel_file_path6 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2023_trackman1.xlsx'
excel_file_path7 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2023_trackman2.xlsx'
#excel_file_path8 = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Trackman/2019_winter_trackman.xlsx'
#sheet_name1 = '工作表1'
sheet_name = 'Sheet1'

In [3]:
#track = pd.read_excel(excel_file_path, sheet_name=sheet_name1)
track_2018 = pd.read_excel(excel_file_path1, sheet_name=sheet_name)
track_2019 = pd.read_excel(excel_file_path2, sheet_name=sheet_name)
track_2020 = pd.read_excel(excel_file_path3, sheet_name=sheet_name)
track_2021 = pd.read_excel(excel_file_path4, sheet_name=sheet_name)
track_2022 = pd.read_excel(excel_file_path5, sheet_name=sheet_name)
track_2023_1 = pd.read_excel(excel_file_path6, sheet_name=sheet_name)
track_2023_2 = pd.read_excel(excel_file_path7, sheet_name=sheet_name)
#track_winter_19 = pd.read_excel(excel_file_path8, sheet_name=sheet_name)

In [4]:
col=['Batter','PlayResult','RunsScored','ExitSpeed','Angle','Distance','GameID']

In [5]:
track_2018= track_2018[col]
track_2019= track_2019[col]
track_2020= track_2020[col]
track_2021= track_2021[col]
track_2022= track_2022[col]
track_2023_1= track_2023_1[col]
track_2023_2= track_2023_2[col]
#track_winter_19=track_winter_19[col]

In [6]:
data1 = pd.concat([track_2019, track_2018], ignore_index=True)
data2 = pd.concat([data1, track_2020], ignore_index=True)
data3 = pd.concat([data2, track_2021], ignore_index=True)
data4 = pd.concat([data3, track_2022], ignore_index=True)
data5 = pd.concat([data4, track_2023_1], ignore_index=True)
#data6 = pd.concat([data5, track_winter_19], ignore_index=True)
data = pd.concat([data5, track_2023_2], ignore_index=True)

In [7]:
playresult_items =  data['PlayResult'].unique()
playresult_items

array(['Undefined', 'Out', 'Single', 'HomeRun', 'Double', 'Triple',
       'Sacrifice', 'Error', 'FieldersChoice', 'StolenBase',
       'CaughtStealing'], dtype=object)

In [8]:
data['Year'] = data['GameID'].str[:4]

# Display the DataFrame

In [9]:
data

Batter  PlayResult  RunsScored  ExitSpeed      Angle  \
0         Lan, Yin-Lun   Undefined           0  72.476293  45.066912   
1         Lan, Yin-Lun   Undefined           0        NaN        NaN   
2         Lan, Yin-Lun         Out           0        NaN        NaN   
3       Chen, Chen-Wei   Undefined           0        NaN        NaN   
4       Chen, Chen-Wei   Undefined           0        NaN        NaN   
...                ...         ...         ...        ...        ...   
98122  Chang, Cheng-Yu      Single           0  81.775520 -10.410349   
98123  Chu, Hsiang-Lin  StolenBase           0        NaN        NaN   
98124  Chu, Hsiang-Lin   Undefined           0  75.694330  74.321846   
98125  Chu, Hsiang-Lin   Undefined           0        NaN        NaN   
98126  Chu, Hsiang-Lin   Sacrifice           1  83.649100  38.015992   

        Distance               GameID  Year  
0            NaN  20190326-Brothers-1  2019  
1            NaN  20190326-Brothers-1  2019  
2            NaN  20190326-Brothers-1  2019  
3            NaN  20190326-Brothers-1  2019  
4            NaN  20190326-Brothers-1  2019  
...          ...                  ...   ...  
98122   16.10865    20231014-Douliu-1  2023  
98123        NaN    20231014-Douliu-1  2023  
98124        NaN    20231014-Douliu-1  2023  
98125        NaN    20231014-Douliu-1  2023  
98126  293.10795    20231014-Douliu-1  2023  

[98127 rows x 8 columns]

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97733 entries, 0 to 98126
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Batter      97727 non-null  object 
 1   PlayResult  97733 non-null  object 
 2   RunsScored  97733 non-null  int64  
 3   ExitSpeed   27098 non-null  float64
 4   Angle       27200 non-null  float64
 5   Distance    22545 non-null  float64
 6   GameID      97733 non-null  object 
 7   Year        97733 non-null  object 
dtypes: float64(3), int64(1), object(4)
memory usage: 6.7+ MB


In [17]:
playresult_items = data['PlayResult'].unique()
playresult_items

array(['Undefined', 'Out', 'Single', 'HomeRun', 'Double', 'Triple',
       'Sacrifice', 'FieldersChoice'], dtype=object)

In [12]:
#data.to_excel('Trackman2018~2023.xlsx', index=False)

In [13]:
data['ExitSpeed'] = data['ExitSpeed'].abs()
data['Distance'] = data['Distance'].abs()

In [14]:
ExitSpeed_items = data['ExitSpeed'].unique()
ExitSpeed_items

array([72.47629256,         nan, 63.72540817, ..., 81.77552   ,
       75.69433   , 83.6491    ])

In [16]:
result_to_remove = ['Error','FoulBall','StolenBase','CaughtStealing']
data = data[~data['PlayResult'].isin(result_to_remove)]


In [18]:
def calculate_so_go_count(series):
    sf_count = (series == 'Sacrifice').sum()
    hr_count = (series == 'HomeRun').sum()
    _3b_count = (series == 'Triple').sum()
    _2b_count = (series == 'Double').sum()
    _1b_count = (series == 'Single').sum()
    out_count = (series == 'Out').sum()
    E_count = (series == 'Error').sum()
    FC_count = (series == 'FieldersChoice').sum()
    return pd.Series({'HomeRun':hr_count,
                      'Sacrifice': sf_count,
                      'Triple': _3b_count,
                      'Double': _2b_count,
                      'Single': _1b_count,
                      'Out': out_count,
                     'Error':E_count,
                     'FieldersChoice':FC_count})

In [19]:
result_counts = data.groupby(['ExitSpeed', 'Angle','Distance'])['PlayResult'].apply(calculate_so_go_count).reset_index()
result_counts = result_counts.rename(columns={'level_3': '打席結果', 'PlayResult': '次數'})
result_counts

ExitSpeed      Angle  Distance            打席結果  次數
0         0.94736 -37.742209   5.67458         HomeRun   0
1         0.94736 -37.742209   5.67458       Sacrifice   0
2         0.94736 -37.742209   5.67458          Triple   0
3         0.94736 -37.742209   5.67458          Double   0
4         0.94736 -37.742209   5.67458          Single   0
...           ...        ...       ...             ...  ..
179763  128.19649  -3.669939  57.39212          Double   0
179764  128.19649  -3.669939  57.39212          Single   0
179765  128.19649  -3.669939  57.39212             Out   0
179766  128.19649  -3.669939  57.39212           Error   0
179767  128.19649  -3.669939  57.39212  FieldersChoice   0

[179768 rows x 5 columns]

In [20]:
result_counts['次數'] = result_counts['次數'].astype(int)

final_resault = pd.pivot_table(result_counts, index=['ExitSpeed', 'Angle','Distance'], columns='打席結果', values='次數', aggfunc='sum', fill_value=0)

final_resault

打席結果                           Double  Error  FieldersChoice  HomeRun  Out  \
ExitSpeed Angle      Distance                                                
0.94736   -37.742209 5.67458        0      0               0        0    0   
4.09526   -0.580412  3.51928        0      0               0        0    0   
5.74284   -52.770014 2.05353        0      0               0        0    0   
6.73813   -8.290806  5.64141        0      0               0        0    0   
7.26806   -26.366751 6.34785        0      0               0        0    0   
...                               ...    ...             ...      ...  ...   
125.34681 -28.157260 4.08650        0      0               0        0    0   
125.42485 -35.965647 0.68466        0      0               0        0    0   
126.66099 -2.068516  61.70787       0      0               0        0    0   
127.05363 -44.418996 0.43615        0      0               0        0    0   
128.19649 -3.669939  57.39212       0      0               0        0    0   

打席結果                           Sacrifice  Single  Triple  
ExitSpeed Angle      Distance                             
0.94736   -37.742209 5.67458           0       0       0  
4.09526   -0.580412  3.51928           0       0       0  
5.74284   -52.770014 2.05353           0       0       0  
6.73813   -8.290806  5.64141           0       0       0  
7.26806   -26.366751 6.34785           0       0       0  
...                                  ...     ...     ...  
125.34681 -28.157260 4.08650           0       0       0  
125.42485 -35.965647 0.68466           0       0       0  
126.66099 -2.068516  61.70787          0       0       0  
127.05363 -44.418996 0.43615           0       0       0  
128.19649 -3.669939  57.39212          0       0       0  

[22471 rows x 8 columns]

In [21]:
final_resault['安打']=final_resault['Double']+final_resault['Single']+final_resault['Triple']+final_resault['HomeRun']
final_resault['長打']=final_resault['Double']+final_resault['Triple']+final_resault['HomeRun']
final_resault['出局機率']=final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']/final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']+final_resault['Double']+final_resault['Single']+final_resault['Triple']+final_resault['HomeRun']
final_resault['一安機率']=final_resault['Single']/final_resault['安打']+final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']
final_resault['二安機率']=final_resault['Double']/final_resault['安打']+final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']
final_resault['三安機率']=final_resault['Triple']/final_resault['安打']+final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']
final_resault['全壘打機率']=final_resault['HomeRun']/final_resault['安打']+final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']


#final_resault['安打機率']=final_resault['安打']/final_resault['安打']+final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']
#final_resault['長打機率']=final_resault['長打']/final_resault['安打']+final_resault['Out']+final_resault['Sacrifice']+final_resault['Error']
#final_resault['出局機率']=final_resault['出局']/final_resault['Double']+final_resault['Single']+final_resault['Triple']+final_resault['HomeRun']+final_resault['出局']

In [22]:
final_resault

打席結果                           Double  Error  FieldersChoice  HomeRun  Out  \
ExitSpeed Angle      Distance                                                
0.94736   -37.742209 5.67458        0      0               0        0    0   
4.09526   -0.580412  3.51928        0      0               0        0    0   
5.74284   -52.770014 2.05353        0      0               0        0    0   
6.73813   -8.290806  5.64141        0      0               0        0    0   
7.26806   -26.366751 6.34785        0      0               0        0    0   
...                               ...    ...             ...      ...  ...   
125.34681 -28.157260 4.08650        0      0               0        0    0   
125.42485 -35.965647 0.68466        0      0               0        0    0   
126.66099 -2.068516  61.70787       0      0               0        0    0   
127.05363 -44.418996 0.43615        0      0               0        0    0   
128.19649 -3.669939  57.39212       0      0               0        0    0   

打席結果                           Sacrifice  Single  Triple  安打  長打  出局機率  一安機率  \
ExitSpeed Angle      Distance                                                  
0.94736   -37.742209 5.67458           0       0       0   0   0   NaN   NaN   
4.09526   -0.580412  3.51928           0       0       0   0   0   NaN   NaN   
5.74284   -52.770014 2.05353           0       0       0   0   0   NaN   NaN   
6.73813   -8.290806  5.64141           0       0       0   0   0   NaN   NaN   
7.26806   -26.366751 6.34785           0       0       0   0   0   NaN   NaN   
...                                  ...     ...     ...  ..  ..   ...   ...   
125.34681 -28.157260 4.08650           0       0       0   0   0   NaN   NaN   
125.42485 -35.965647 0.68466           0       0       0   0   0   NaN   NaN   
126.66099 -2.068516  61.70787          0       0       0   0   0   NaN   NaN   
127.05363 -44.418996 0.43615           0       0       0   0   0   NaN   NaN   
128.19649 -3.669939  57.39212          0       0       0   0   0   NaN   NaN   

打席結果                           二安機率  三安機率  全壘打機率  
ExitSpeed Angle      Distance                     
0.94736   -37.742209 5.67458    NaN   NaN    NaN  
4.09526   -0.580412  3.51928    NaN   NaN    NaN  
5.74284   -52.770014 2.05353    NaN   NaN    NaN  
6.73813   -8.290806  5.64141    NaN   NaN    NaN  
7.26806   -26.366751 6.34785    NaN   NaN    NaN  
...                             ...   ...    ...  
125.34681 -28.157260 4.08650    NaN   NaN    NaN  
125.42485 -35.965647 0.68466    NaN   NaN    NaN  
126.66099 -2.068516  61.70787   NaN   NaN    NaN  
127.05363 -44.418996 0.43615    NaN   NaN    NaN  
128.19649 -3.669939  57.39212   NaN   NaN    NaN  

[22471 rows x 15 columns]

In [33]:
final_resault.fillna(0, inplace=True)

In [22]:
final_resault.reset_index(inplace=True)

In [34]:
final_resault.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23640 entries, 0 to 23639
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   ExitSpeed       23640 non-null  float64
 1   Angle           23640 non-null  float64
 2   Distance        23640 non-null  float64
 3   Double          23640 non-null  int32  
 4   Error           23640 non-null  int32  
 5   FieldersChoice  23640 non-null  int32  
 6   HomeRun         23640 non-null  int32  
 7   Out             23640 non-null  int32  
 8   Sacrifice       23640 non-null  int32  
 9   Single          23640 non-null  int32  
 10  Triple          23640 non-null  int32  
 11  安打              23640 non-null  int32  
 12  長打              23640 non-null  int32  
 13  出局機率            23640 non-null  float64
 14  安打機率            23640 non-null  float64
 15  長打機率            23640 non-null  float64
 16  ExitSpeed(KM)   23640 non-null  float64
dtypes: float64(7), int32(10)
memory

In [35]:
final_resault['ExitSpeed(KM)']=final_resault['ExitSpeed']*1.60934

In [36]:
final_resault

打席結果   ExitSpeed      Angle  Distance  Double  Error  FieldersChoice  HomeRun  \
0        0.94736 -37.742209   5.67458       0      0               0        0   
1        4.09526  -0.580412   3.51928       0      0               0        0   
2        5.74284 -52.770014   2.05353       0      0               0        0   
3        6.73813  -8.290806   5.64141       0      0               0        0   
4        7.26806 -26.366751   6.34785       0      0               0        0   
...          ...        ...       ...     ...    ...             ...      ...   
23635  125.34681 -28.157260   4.08650       0      0               0        0   
23636  125.42485 -35.965647   0.68466       0      0               0        0   
23637  126.66099  -2.068516  61.70787       0      0               0        0   
23638  127.05363 -44.418996   0.43615       0      0               0        0   
23639  128.19649  -3.669939  57.39212       0      0               0        0   

打席結果   Out  Sacrifice  Single  Triple  安打  長打  出局機率  安打機率  長打機率  ExitSpeed(KM)  
0        0          0       0       0   0   0   0.0   0.0   0.0       1.524624  
1        0          0       0       0   0   0   0.0   0.0   0.0       6.590666  
2        0          0       0       0   0   0   0.0   0.0   0.0       9.242182  
3        0          0       0       0   0   0   0.0   0.0   0.0      10.843942  
4        0          0       0       0   0   0   0.0   0.0   0.0      11.696780  
...    ...        ...     ...     ...  ..  ..   ...   ...   ...            ...  
23635    0          0       0       0   0   0   0.0   0.0   0.0     201.725635  
23636    0          0       0       0   0   0   0.0   0.0   0.0     201.851228  
23637    0          0       0       0   0   0   0.0   0.0   0.0     203.840598  
23638    0          0       0       0   0   0   0.0   0.0   0.0     204.472489  
23639    0          0       0       0   0   0   0.0   0.0   0.0     206.311739  

[23640 rows x 17 columns]

In [37]:
result_items = final_resault['出局機率'].unique()
result_items

array([0., 1.])

### LinearRegression

In [27]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score

In [38]:
X = final_resault[['ExitSpeed(KM)', 'Angle']]
#,'Double','HomeRun','Out','Sacrifice','Single','Triple']]
y = final_resault[['安打機率', '長打機率','出局機率','Distance']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=40)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

# 打印预测结果
print(predictions)

[[-2.51547335e-02 -6.64088642e-02  3.75763236e-01  7.35891492e+01]
 [ 4.82048848e-02 -1.13937414e-03  3.53212729e-01  1.98031100e+02]
 [ 1.19841712e-01  3.99166004e-02  3.56823519e-01  2.41356524e+02]
 ...
 [ 4.44213028e-01  1.49749090e-01  4.59139346e-01  1.75278757e+02]
 [ 1.67343249e-02 -4.51453398e-02  3.80975217e-01  8.94644067e+01]
 [ 3.46375261e-01  1.02488488e-01  4.44249994e-01  1.46485630e+02]]


In [39]:
print('accuracy:', model.score(X_test, y_test))

accuracy: 0.21045748455780192


In [40]:
def predict_outcome_probability(ExitSpeed, Angle):
    prediction = model.predict([[ExitSpeed, Angle]])
    
    probability = {
        '安打機率': prediction[0][0],
        '長打機率': prediction[0][1],
        '出局機率': prediction[0][2],
        'Distance': prediction[0][3],
    }
    
    return probability

ExitSpeed = 110
Angle = 0
result = predict_outcome_probability(ExitSpeed, Angle)
print(result)

{'安打機率': 0.1526712496237156, '長打機率': 0.009836106449797433, '出局機率': 0.4137356043981752, 'Distance': 92.63923098572837}


C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
